spring:
  jpa:
    properties:
      com.oracle.coherence.hibernate.cache.cache_config_file_path: remote-hibernate-second-level-cache-config.xml
      com.oracle.coherence.hibernate.cache.start_cache_server: false
  datasource:
    url: jdbc:hsqldb:hsql://localhost:9001/maindb
    username: coherence
    password: rocks